---
version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: localhub.etod.me/otezvikentiy/php7.2-fpm:0.0.13
    container_name: app
    restart: unless-stopped
    tty: true
    env_file:
      - ./.env/php.env
    working_dir: /var/www
    hostname: jaheshfund.mobtaker.local
    networks: 
      - app-network
    ports:
      - "2222:22"
    volumes:
      - ./lumen-app/jaheshfund:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - /etc/hosts:/etc/hosts:ro
      - ./ssh_accounts/authorized_keys:/home/www/.ssh/authorized_keys:ro
      - ./ssh_accounts/sshd_config:/etc/ssh/sshd_config:ro
      - /etc/ssh/banner.txt:/etc/ssh/banner.txt:ro
  
  #Nginx Service
  webserver:
    image: localhub.etod.me/nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
    networks:
      - app-network
    volumes:
      - ./lumen-app/jaheshfund:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d/
      - ./nginx/log:/var/log/nginx
      
    
  #MySQL Service
  mysql:
    image: localhub.etod.me/mysql:5.7.22
    container_name: db1
    restart: unless-stopped
    tty: true
    ports:
      - "3306"
    env_file:
      - ./.env/db1.env
    networks:
      - app-network
    volumes:
      - dbdata1:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf


  loggingdb:
    image: localhub.etod.me/mysql:5.7.22
    container_name: db2
    restart: unless-stopped
    tty: true
    ports:
      - "3306"
    env_file:
      - ./.env/db2.env
    networks:
      - app-network
    volumes:
      - dbdata2:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf


  #PHPMyAdmin
  phpmyadmin1:
    image: localhub.etod.me/phpmyadmin/phpmyadmin
    container_name: phpmyadmin1
    depends_on:
      - mysql
    ports:
      - "10080:80"
    env_file:
      - ./.env/phpmyadmin1.env
    restart: unless-stopped
    networks:
      - app-network
      

  phpmyadmin2:
    image: localhub.etod.me/phpmyadmin/phpmyadmin
    container_name: phpmyadmin2
    depends_on:
      - loggingdb
    ports:
      - "10081:80"
    env_file:
      - ./.env/phpmyadmin2.env
    restart: unless-stopped
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.29.12.0/24

volumes:
  dbdata1:
    driver: local
  dbdata2:
    driver: local
